<?php
/**
 * CpeErrorValidationTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Greenter\Sunat\GRE
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * SUNAT GRE API
 *
 * PLATAFORMA NUEVA GRE.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: me@giansalex.dev
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.3.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Greenter\Sunat\GRE\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * CpeErrorValidationTest Class Doc Comment
 *
 * @category    Class
 * @description CpeErrorValidation
 * @package     Greenter\Sunat\GRE
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class CpeErrorValidationTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "CpeErrorValidation"
     */
    public function testCpeErrorValidation()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "cod"
     */
    public function testPropertyCod()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "msg"
     */
    public function testPropertyMsg()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "errors"
     */
    public function testPropertyErrors()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
