<?php
/**
 * StatusResponseErrorTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Greenter\Sunat\GRE
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * SUNAT GRE API
 *
 * PLATAFORMA NUEVA GRE.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: me@giansalex.dev
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.3.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Greenter\Sunat\GRE\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * StatusResponseErrorTest Class Doc Comment
 *
 * @category    Class
 * @description Solo se generará este nodo si codRespuesta es 99
 * @package     Greenter\Sunat\GRE
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class StatusResponseErrorTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "StatusResponseError"
     */
    public function testStatusResponseError()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "num_error"
     */
    public function testPropertyNumError()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "des_error"
     */
    public function testPropertyDesError()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
